/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bibliotecaapp.vista;

import bibliotecaapp.controlador.ControladorLibro;
import bibliotecaapp.modelo.Libro;
import bibliotecaapp.modelo.Usuario;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yeisson.villamil
 */
public class DashboardCliente extends javax.swing.JPanel {

    private Usuario usuario;
    private ControladorLibro controladorLibro;

    // Modelos para las tablas
    private DefaultTableModel modeloDisponibles;
    private DefaultTableModel modeloPrestados;
    private DefaultTableModel modeloDevueltos;

    public DashboardCliente(Usuario usuario) {
        initComponents();
        this.usuario = usuario;

        // Usamos la misma instancia compartida de libros (por ejemplo, con una lista estática)
        controladorLibro = new ControladorLibro();

        // Configurar modelos de tabla (se asume que has colocado tres JTables en un JTabbedPane)
        // Por ejemplo, los nombres de variable de los JTables son:
        //   tablaLibrosDisponibles, tablaLibrosPrestados y tablaLibrosDevueltos.
        modeloDisponibles = (DefaultTableModel) tablaLibrosDisponibles.getModel();
        modeloPrestados = (DefaultTableModel) tablaLibrosPrestados.getModel();
        modeloDevueltos = (DefaultTableModel) tablaLibrosDevueltos.getModel();

        modeloDisponibles.setColumnIdentifiers(new Object[]{"Título", "Autor", "ISBN"});
        modeloPrestados.setColumnIdentifiers(new Object[]{"Título", "Autor", "ISBN"});
        modeloDevueltos.setColumnIdentifiers(new Object[]{"Título", "Autor", "ISBN"});

        actualizarTablaDisponibles();
        actualizarTablaPrestados();
        actualizarTablaDevueltos();
    }

    // Métodos para actualizar cada tabla (se explican a continuación)
    private void actualizarTablaDisponibles() {
        modeloDisponibles.setRowCount(0);
        for (Libro libro : controladorLibro.getListaLibros()) {
            modeloDisponibles.addRow(new Object[]{libro.getTitulo(), libro.getAutor(), libro.getIsbn()});
        }
    }

    private void actualizarTablaPrestados() {
        modeloPrestados.setRowCount(0);
        for (Libro libro : usuario.getLibrosPrestados()) {
            modeloPrestados.addRow(new Object[]{libro.getTitulo(), libro.getAutor(), libro.getIsbn()});
        }
    }

    private void actualizarTablaDevueltos() {
        modeloDevueltos.setRowCount(0);
        for (Libro libro : usuario.getLibrosDevueltos()) {
            modeloDevueltos.addRow(new Object[]{libro.getTitulo(), libro.getAutor(), libro.getIsbn()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaLibrosDisponibles = new javax.swing.JTable();
        botonPedirPrestado = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        botonCerrarSesion = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLibrosPrestados = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        botonDevolverLibro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tablaLibrosDevueltos = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();

        jTabbedPane1.setBackground(new java.awt.Color(204, 204, 204));
        jTabbedPane1.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));

        jScrollPane1.setBackground(new java.awt.Color(204, 204, 255));

        tablaLibrosDisponibles.setBackground(new java.awt.Color(204, 204, 255));
        tablaLibrosDisponibles.setFont(new java.awt.Font("Roboto Medium", 0, 14)); // NOI18N
        tablaLibrosDisponibles.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tablaLibrosDisponibles);

        botonPedirPrestado.setBackground(new java.awt.Color(204, 204, 204));
        botonPedirPrestado.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        botonPedirPrestado.setText("Pedir Prestado");
        botonPedirPrestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedirPrestadoActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(204, 204, 255));
        jLabel1.setFont(new java.awt.Font("Roboto", 3, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Libros disponibles");

        botonCerrarSesion.setBackground(new java.awt.Color(204, 204, 204));
        botonCerrarSesion.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        botonCerrarSesion.setText("Cerrar sesión");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(209, 209, 209)
                        .addComponent(botonPedirPrestado)
                        .addGap(48, 48, 48)
                        .addComponent(botonCerrarSesion))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 542, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addComponent(jLabel1)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(botonPedirPrestado)
                    .addComponent(botonCerrarSesion))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Disponibles", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 204, 204));

        tablaLibrosPrestados.setBackground(new java.awt.Color(204, 204, 255));
        tablaLibrosPrestados.setFont(new java.awt.Font("Roboto", 1, 14)); // NOI18N
        tablaLibrosPrestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaLibrosPrestados);

        jLabel2.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("Libros prestados");

        botonDevolverLibro.setBackground(new java.awt.Color(204, 204, 204));
        botonDevolverLibro.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        botonDevolverLibro.setText("Devolver");
        botonDevolverLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDevolverLibroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(308, 308, 308)
                                .addComponent(botonDevolverLibro))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(291, 291, 291)
                                .addComponent(jLabel2)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(botonDevolverLibro)
                .addContainerGap(130, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Prestados", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 204, 204));

        tablaLibrosDevueltos.setBackground(new java.awt.Color(204, 204, 255));
        tablaLibrosDevueltos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tablaLibrosDevueltos);

        jLabel3.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 102, 0));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Libros devueltos");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(171, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Devueltos", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 568, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonPedirPrestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedirPrestadoActionPerformed
        int filaSeleccionada = tablaLibrosDisponibles.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un libro disponible", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        // Se asume que la columna 2 contiene el ISBN
        String isbn = modeloDisponibles.getValueAt(filaSeleccionada, 2).toString();

        // Verificar si el libro ya está en la lista de prestados
        for (Libro l : usuario.getLibrosPrestados()) {
            if (l.getIsbn().equals(isbn)) {
                JOptionPane.showMessageDialog(this, "Ya tienes prestado este libro", "Información", JOptionPane.INFORMATION_MESSAGE);
                return;
            }
        }

        // Si no se encuentra, se añade a la lista de libros prestados
        Libro libroSeleccionado = controladorLibro.buscarLibroPorISBN(isbn);
        if (libroSeleccionado != null) {
            usuario.getLibrosPrestados().add(libroSeleccionado);
            JOptionPane.showMessageDialog(this, "Libro prestado correctamente");
            actualizarTablaPrestados();
        }
    }//GEN-LAST:event_botonPedirPrestadoActionPerformed

    private void botonDevolverLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDevolverLibroActionPerformed
        int filaSeleccionada = tablaLibrosPrestados.getSelectedRow();
        if (filaSeleccionada < 0) {
            JOptionPane.showMessageDialog(this, "Seleccione un libro para devolver", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Se asume que la columna 2 contiene el ISBN
        String isbn = modeloPrestados.getValueAt(filaSeleccionada, 2).toString();

        Libro libroADevolver = null;
        for (Libro l : usuario.getLibrosPrestados()) {
            if (l.getIsbn().equals(isbn)) {
                libroADevolver = l;
                break;
            }
        }
        if (libroADevolver != null) {
            usuario.getLibrosPrestados().remove(libroADevolver);
            usuario.getLibrosDevueltos().add(libroADevolver);
            JOptionPane.showMessageDialog(this, "Libro devuelto correctamente");
            actualizarTablaPrestados();
            actualizarTablaDevueltos();
        }
    }//GEN-LAST:event_botonDevolverLibroActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
                int confirmacion = JOptionPane.showConfirmDialog(this,
                "¿Desea cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Se obtiene el contenedor padre, que es el JTabbedPane donde está agregado este panel.
            Container parent = this.getParent();
            if (parent instanceof JTabbedPane) {
                JTabbedPane tabbedPane = (JTabbedPane) parent;
                // Se elimina este dashboard (la pestaña actual)
                tabbedPane.remove(this);
                // Se selecciona la pestaña principal. Asumiremos que la pestaña 0 es "Registro" o "Login"
                tabbedPane.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_botonCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonDevolverLibro;
    private javax.swing.JButton botonPedirPrestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable tablaLibrosDevueltos;
    private javax.swing.JTable tablaLibrosDisponibles;
    private javax.swing.JTable tablaLibrosPrestados;
    // End of variables declaration//GEN-END:variables
}
