/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bibliotecaapp.vista;

import bibliotecaapp.controlador.ControladorLibro;
import bibliotecaapp.modelo.Libro;
import java.awt.Container;
import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author yeisson.villamil
 */
public class DashboardCliente extends javax.swing.JPanel {

    private DefaultTableModel modelo;
    private ControladorLibro controladorLibro;

    public DashboardCliente() {
        initComponents();
        controladorLibro = new ControladorLibro();
        modelo = (DefaultTableModel) tablaLibrosCliente.getModel();
        modelo.setColumnIdentifiers(new Object[]{"Título", "Autor", "ISBN"});

        actualizarTabla();
    }

    private void actualizarTabla() {
        modelo.setRowCount(0);
        for (Libro libro : controladorLibro.getListaLibros()) {
            modelo.addRow(new Object[]{libro.getTitulo(), libro.getAutor(), libro.getIsbn()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaLibrosCliente = new javax.swing.JTable();
        botonPedirPrestado = new javax.swing.JButton();
        botonCerrarSesion = new javax.swing.JButton();

        jLabel1.setText("Catálogo de Libros");

        tablaLibrosCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaLibrosCliente);

        jScrollPane1.setViewportView(jScrollPane2);

        botonPedirPrestado.setText("Pedir Prestado");
        botonPedirPrestado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPedirPrestadoActionPerformed(evt);
            }
        });

        botonCerrarSesion.setText("Cerrar sesión");
        botonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 91, Short.MAX_VALUE)
                        .addComponent(botonCerrarSesion)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(botonPedirPrestado)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addComponent(botonCerrarSesion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(botonPedirPrestado)
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botonPedirPrestadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPedirPrestadoActionPerformed
        int filaSeleccionada = tablaLibrosCliente.getSelectedRow();
        if (filaSeleccionada >= 0) {
            String titulo = modelo.getValueAt(filaSeleccionada, 0).toString();
            JOptionPane.showMessageDialog(this, "Has solicitado el préstamo del libro: " + titulo);
            // Aquí podrías implementar la lógica para registrar el préstamo.
        } else {
            JOptionPane.showMessageDialog(this, "Seleccione un libro para pedir prestado.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_botonPedirPrestadoActionPerformed

    private void botonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCerrarSesionActionPerformed
        int confirmacion = JOptionPane.showConfirmDialog(this,
            "¿Desea cerrar sesión?", "Cerrar sesión", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            // Se obtiene el contenedor padre, que es el JTabbedPane donde está agregado este panel.
            Container parent = this.getParent();
            if (parent instanceof JTabbedPane) {
                JTabbedPane tabbedPane = (JTabbedPane) parent;
                // Se elimina este dashboard (la pestaña actual)
                tabbedPane.remove(this);
                // Se selecciona la pestaña principal. Asumiremos que la pestaña 0 es "Registro" o "Login"
                tabbedPane.setSelectedIndex(0);
            }
        }
    }//GEN-LAST:event_botonCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCerrarSesion;
    private javax.swing.JButton botonPedirPrestado;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaLibrosCliente;
    // End of variables declaration//GEN-END:variables
}
